# Site settings
title: Glasscubes help
email: it@leprosymission.org
description: Documenting 'stuff' on Glasscubes. Work in progress.
url: "https://tlmi.glasscubes.com"
twitter_username: jonnyoftsang
github_username:  jon-tlmi
